if: tag IS present
language: java
before_install: chmod +x gradlew
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - |
    curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache" \
         -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
         -H "X-Auth-Key: $CLOUDFLARE_KEY" \
         -H "Content-Type: application/json" \
         --data '{"files":["https://www.polyr.xyz/","https://www.polyr.xyz/index","https://www.polyr.xyz/index.html"]}'
